target 'Business-Logic-Layer', :exclusive => true do
  pod "Business-Logic-Layer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Business-Logic-Layer", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
