target 'Business-Logic-Layer', :exclusive => true do
  pod "Business-Logic-Layer", :path => "../"
  pod "IOS_Collection_Code", :path => "../../../collect/IOS_Collection_Code"
end

target 'Tests', :exclusive => true do
  pod "Business-Logic-Layer", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
