target 'JBTabBarController', :exclusive => true do
  pod "JBTabBarController", :path => "../"
  #pod 'UIColor-HexString', '~> 1.1.0'
end

target 'Tests', :exclusive => true do
  pod "JBTabBarController", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
