# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/google-api-services-youtube.xcworkspace -scheme google-api-services-youtube -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
