source 'https://github.com/CocoaPods/Specs.git'

# pod 'Reveal-iOS-SDK'


pod "JBTabBarController", :path => "../lib/JBTabBarController"
pod "WHTopTabBarController", :path => "../lib/WHTopTabBarController"
pod "YKMediaPlayerKit", :path => "../lib/YKMediaPlayerKit"

# pod 'Reveal-iOS-SDK'

pod "XCDYouTubeKit", :path => "../lib/XCDYouTubeKit"
pod "AAPullToRefresh", :path => "../lib/AAPullToRefresh"

pod "IOS_Collection_Code", :path => "../collect/IOS_Collection_Code"

pod "Business-Logic-Layer", :path => "../layers/Business-Logic-Layer"

pod "google-api-services-youtube", :path => "../layers/google-api-services-youtube"

pod "YoutubeCollectionView", :path => "../ipad/YoutubeCollectionView"

pod "VideoWatchDetailViewControlleriPad", :path => "../module/VideoWatchDetailViewControlleriPad"



