/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-23 at 17:34:18 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.youtube.model;

/**
 * Ratings schemes. The country-specific ratings are mostly for movies and shows.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the YouTube Data API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ContentRating extends com.google.api.client.json.GenericJson {

  /**
   * Rating system in Australia - Australian Classification Board
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String acbRating;

  /**
   * Rating system for Italy - Autorit� per le Garanzie nelle Comunicazioni
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agcomRating;

  /**
   * Rating system for Chile - Asociaci�n Nacional de Televisi�n
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String anatelRating;

  /**
   * British Board of Film Classification
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bbfcRating;

  /**
   * Rating system for Thailand - Board of Filmand Video Censors
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bfvcRating;

  /**
   * Rating system for Austria - Bundesministeriums f�r Unterricht, Kunst und Kultur!
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bmukkRating;

  /**
   * Rating system for Canadian TV - Canadian TV Classification System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catvRating;

  /**
   * Rating system for French Canadian TV - Regie du cinema
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catvfrRating;

  /**
   * Rating system in India - Central Board of Film Certification
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cbfcRating;

  /**
   * Rating system for Chile - Consejo de Calificaci�n Cinematogr�fica
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cccRating;

  /**
   * Rating system for Portugal - Comiss�o de Classifica��o de Espect�culos
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cceRating;

  /**
   * Rating system for Switzerland - Switzerland Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String chfilmRating;

  /**
   * Canadian Home Video Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String chvrsRating;

  /**
   * Rating system for Belgium - Belgium Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cicfRating;

  /**
   * Rating system for Romania - CONSILIUL NATIONAL AL AUDIOVIZUALULUI - CNA
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cnaRating;

  /**
   * Rating system for France - Conseil sup�rieur de l?audiovisuel
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String csaRating;

  /**
   * Rating system for Luxembourg - Commission de surveillance de la classification des films
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cscfRating;

  /**
   * Rating system for Czech republic - Czech republic Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String czfilmRating;

  /**
   * Rating system in Brazil - Department of Justice, Rating, Titles and Qualification
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String djctqRating;

  /**
   * Rating system for Estonia - Estonia Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eefilmRating;

  /**
   * Rating system for Egypt - Egypt Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String egfilmRating;

  /**
   * Rating system in Japan - Eiga Rinri Kanri Iinkai
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eirinRating;

  /**
   * Rating system for Malaysia - Film Censorship Board of Malaysia
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fcbmRating;

  /**
   * Rating system for Hong kong - Office for Film, Newspaper and Article Administration
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fcoRating;

  /**
   * Rating system in France - French Minister of Culture
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fmocRating;

  /**
   * Rating system for South africa - Film & Publication Board
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fpbRating;

  /**
   * Rating system in Germany - Voluntary Self Regulation of the Movie Industry
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fskRating;

  /**
   * Rating system for Greece - Greece Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String grfilmRating;

  /**
   * Rating system in Spain - Instituto de Cinematografia y de las Artes Audiovisuales
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String icaaRating;

  /**
   * Rating system in Ireland - Irish Film Classification Office
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ifcoRating;

  /**
   * Rating system for Israel - Israel Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ilfilmRating;

  /**
   * Rating system for Argentina - Instituto Nacional de Cine y Artes Audiovisuales
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String incaaRating;

  /**
   * Rating system for Kenya - Kenya Film Classification Board
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kfcbRating;

  /**
   * Rating system for Netherlands - Nederlands Instituut voor de Classificatie van Audiovisuele
   * Media
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kijkwijzerRating;

  /**
   * Rating system in South Korea - Korea Media Rating Board
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kmrbRating;

  /**
   * Rating system for Indonesia - Lembaga Sensor Film
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lsfRating;

  /**
   * Rating system for Malta - Film Age-Classification Board
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mccaaRating;

  /**
   * Rating system for Denmark - The Media Council for Children and Young People
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mccypRating;

  /**
   * Rating system for Singapore - Media Development Authority
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mdaRating;

  /**
   * Rating system for Norway - Medietilsynet
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String medietilsynetRating;

  /**
   * Rating system for Finland - Finnish Centre for Media Education and Audiovisual Media
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mekuRating;

  /**
   * Rating system in Italy - Ministero dei Beni e delle Attivita Culturali e del Turismo
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mibacRating;

  /**
   * Rating system for Colombia - MoC
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mocRating;

  /**
   * Rating system for Taiwan - Ministry of Culture - Tawan
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String moctwRating;

  /**
   * Motion Picture Association of America rating for the content.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mpaaRating;

  /**
   * Rating system for Philippines - MOVIE AND TELEVISION REVIEW AND CLASSIFICATION BOARD
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mtrcbRating;

  /**
   * Rating system for Maldives - National Bureau of Classification
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nbcRating;

  /**
   * Rating system for Poland - National Broadcasting Council
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nbcplRating;

  /**
   * Rating system for Bulgaria - National Film Centre
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nfrcRating;

  /**
   * Rating system for Nigeria - National Film and Video Censors Board
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nfvcbRating;

  /**
   * Rating system for Latvia - National Film Center of Latvia
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nkclvRating;

  /**
   * Rating system in New Zealand - Office of Film and Literature Classification
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String oflcRating;

  /**
   * Rating system for Peru - Peru Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pefilmRating;

  /**
   * Rating system for Hungary - Rating Committee of the National Office of Film
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rcnofRating;

  /**
   * Rating system for Venezuela - SiBCI
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String resorteviolenciaRating;

  /**
   * Rating system in Mexico - General Directorate of Radio, Television and Cinematography
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rtcRating;

  /**
   * Rating system for Ireland - Raidi� Teilif�s �ireann
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rteRating;

  /**
   * Rating system in Russia
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String russiaRating;

  /**
   * Rating system for Slovakia - Slovakia Rating System
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String skfilmRating;

  /**
   * Rating system for Iceland - SMAIS
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String smaisRating;

  /**
   * Rating system for Sweden - Statens medier�d (National Media Council)
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String smsaRating;

  /**
   * TV Parental Guidelines rating of the content.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tvpgRating;

  /**
   * Internal YouTube rating.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ytRating;

  /**
   * Rating system in Australia - Australian Classification Board
   * @return value or {@code null} for none
   */
  public java.lang.String getAcbRating() {
    return acbRating;
  }

  /**
   * Rating system in Australia - Australian Classification Board
   * @param acbRating acbRating or {@code null} for none
   */
  public ContentRating setAcbRating(java.lang.String acbRating) {
    this.acbRating = acbRating;
    return this;
  }

  /**
   * Rating system for Italy - Autorit� per le Garanzie nelle Comunicazioni
   * @return value or {@code null} for none
   */
  public java.lang.String getAgcomRating() {
    return agcomRating;
  }

  /**
   * Rating system for Italy - Autorit� per le Garanzie nelle Comunicazioni
   * @param agcomRating agcomRating or {@code null} for none
   */
  public ContentRating setAgcomRating(java.lang.String agcomRating) {
    this.agcomRating = agcomRating;
    return this;
  }

  /**
   * Rating system for Chile - Asociaci�n Nacional de Televisi�n
   * @return value or {@code null} for none
   */
  public java.lang.String getAnatelRating() {
    return anatelRating;
  }

  /**
   * Rating system for Chile - Asociaci�n Nacional de Televisi�n
   * @param anatelRating anatelRating or {@code null} for none
   */
  public ContentRating setAnatelRating(java.lang.String anatelRating) {
    this.anatelRating = anatelRating;
    return this;
  }

  /**
   * British Board of Film Classification
   * @return value or {@code null} for none
   */
  public java.lang.String getBbfcRating() {
    return bbfcRating;
  }

  /**
   * British Board of Film Classification
   * @param bbfcRating bbfcRating or {@code null} for none
   */
  public ContentRating setBbfcRating(java.lang.String bbfcRating) {
    this.bbfcRating = bbfcRating;
    return this;
  }

  /**
   * Rating system for Thailand - Board of Filmand Video Censors
   * @return value or {@code null} for none
   */
  public java.lang.String getBfvcRating() {
    return bfvcRating;
  }

  /**
   * Rating system for Thailand - Board of Filmand Video Censors
   * @param bfvcRating bfvcRating or {@code null} for none
   */
  public ContentRating setBfvcRating(java.lang.String bfvcRating) {
    this.bfvcRating = bfvcRating;
    return this;
  }

  /**
   * Rating system for Austria - Bundesministeriums f�r Unterricht, Kunst und Kultur!
   * @return value or {@code null} for none
   */
  public java.lang.String getBmukkRating() {
    return bmukkRating;
  }

  /**
   * Rating system for Austria - Bundesministeriums f�r Unterricht, Kunst und Kultur!
   * @param bmukkRating bmukkRating or {@code null} for none
   */
  public ContentRating setBmukkRating(java.lang.String bmukkRating) {
    this.bmukkRating = bmukkRating;
    return this;
  }

  /**
   * Rating system for Canadian TV - Canadian TV Classification System
   * @return value or {@code null} for none
   */
  public java.lang.String getCatvRating() {
    return catvRating;
  }

  /**
   * Rating system for Canadian TV - Canadian TV Classification System
   * @param catvRating catvRating or {@code null} for none
   */
  public ContentRating setCatvRating(java.lang.String catvRating) {
    this.catvRating = catvRating;
    return this;
  }

  /**
   * Rating system for French Canadian TV - Regie du cinema
   * @return value or {@code null} for none
   */
  public java.lang.String getCatvfrRating() {
    return catvfrRating;
  }

  /**
   * Rating system for French Canadian TV - Regie du cinema
   * @param catvfrRating catvfrRating or {@code null} for none
   */
  public ContentRating setCatvfrRating(java.lang.String catvfrRating) {
    this.catvfrRating = catvfrRating;
    return this;
  }

  /**
   * Rating system in India - Central Board of Film Certification
   * @return value or {@code null} for none
   */
  public java.lang.String getCbfcRating() {
    return cbfcRating;
  }

  /**
   * Rating system in India - Central Board of Film Certification
   * @param cbfcRating cbfcRating or {@code null} for none
   */
  public ContentRating setCbfcRating(java.lang.String cbfcRating) {
    this.cbfcRating = cbfcRating;
    return this;
  }

  /**
   * Rating system for Chile - Consejo de Calificaci�n Cinematogr�fica
   * @return value or {@code null} for none
   */
  public java.lang.String getCccRating() {
    return cccRating;
  }

  /**
   * Rating system for Chile - Consejo de Calificaci�n Cinematogr�fica
   * @param cccRating cccRating or {@code null} for none
   */
  public ContentRating setCccRating(java.lang.String cccRating) {
    this.cccRating = cccRating;
    return this;
  }

  /**
   * Rating system for Portugal - Comiss�o de Classifica��o de Espect�culos
   * @return value or {@code null} for none
   */
  public java.lang.String getCceRating() {
    return cceRating;
  }

  /**
   * Rating system for Portugal - Comiss�o de Classifica��o de Espect�culos
   * @param cceRating cceRating or {@code null} for none
   */
  public ContentRating setCceRating(java.lang.String cceRating) {
    this.cceRating = cceRating;
    return this;
  }

  /**
   * Rating system for Switzerland - Switzerland Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getChfilmRating() {
    return chfilmRating;
  }

  /**
   * Rating system for Switzerland - Switzerland Rating System
   * @param chfilmRating chfilmRating or {@code null} for none
   */
  public ContentRating setChfilmRating(java.lang.String chfilmRating) {
    this.chfilmRating = chfilmRating;
    return this;
  }

  /**
   * Canadian Home Video Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getChvrsRating() {
    return chvrsRating;
  }

  /**
   * Canadian Home Video Rating System
   * @param chvrsRating chvrsRating or {@code null} for none
   */
  public ContentRating setChvrsRating(java.lang.String chvrsRating) {
    this.chvrsRating = chvrsRating;
    return this;
  }

  /**
   * Rating system for Belgium - Belgium Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getCicfRating() {
    return cicfRating;
  }

  /**
   * Rating system for Belgium - Belgium Rating System
   * @param cicfRating cicfRating or {@code null} for none
   */
  public ContentRating setCicfRating(java.lang.String cicfRating) {
    this.cicfRating = cicfRating;
    return this;
  }

  /**
   * Rating system for Romania - CONSILIUL NATIONAL AL AUDIOVIZUALULUI - CNA
   * @return value or {@code null} for none
   */
  public java.lang.String getCnaRating() {
    return cnaRating;
  }

  /**
   * Rating system for Romania - CONSILIUL NATIONAL AL AUDIOVIZUALULUI - CNA
   * @param cnaRating cnaRating or {@code null} for none
   */
  public ContentRating setCnaRating(java.lang.String cnaRating) {
    this.cnaRating = cnaRating;
    return this;
  }

  /**
   * Rating system for France - Conseil sup�rieur de l?audiovisuel
   * @return value or {@code null} for none
   */
  public java.lang.String getCsaRating() {
    return csaRating;
  }

  /**
   * Rating system for France - Conseil sup�rieur de l?audiovisuel
   * @param csaRating csaRating or {@code null} for none
   */
  public ContentRating setCsaRating(java.lang.String csaRating) {
    this.csaRating = csaRating;
    return this;
  }

  /**
   * Rating system for Luxembourg - Commission de surveillance de la classification des films
   * @return value or {@code null} for none
   */
  public java.lang.String getCscfRating() {
    return cscfRating;
  }

  /**
   * Rating system for Luxembourg - Commission de surveillance de la classification des films
   * @param cscfRating cscfRating or {@code null} for none
   */
  public ContentRating setCscfRating(java.lang.String cscfRating) {
    this.cscfRating = cscfRating;
    return this;
  }

  /**
   * Rating system for Czech republic - Czech republic Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getCzfilmRating() {
    return czfilmRating;
  }

  /**
   * Rating system for Czech republic - Czech republic Rating System
   * @param czfilmRating czfilmRating or {@code null} for none
   */
  public ContentRating setCzfilmRating(java.lang.String czfilmRating) {
    this.czfilmRating = czfilmRating;
    return this;
  }

  /**
   * Rating system in Brazil - Department of Justice, Rating, Titles and Qualification
   * @return value or {@code null} for none
   */
  public java.lang.String getDjctqRating() {
    return djctqRating;
  }

  /**
   * Rating system in Brazil - Department of Justice, Rating, Titles and Qualification
   * @param djctqRating djctqRating or {@code null} for none
   */
  public ContentRating setDjctqRating(java.lang.String djctqRating) {
    this.djctqRating = djctqRating;
    return this;
  }

  /**
   * Rating system for Estonia - Estonia Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getEefilmRating() {
    return eefilmRating;
  }

  /**
   * Rating system for Estonia - Estonia Rating System
   * @param eefilmRating eefilmRating or {@code null} for none
   */
  public ContentRating setEefilmRating(java.lang.String eefilmRating) {
    this.eefilmRating = eefilmRating;
    return this;
  }

  /**
   * Rating system for Egypt - Egypt Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getEgfilmRating() {
    return egfilmRating;
  }

  /**
   * Rating system for Egypt - Egypt Rating System
   * @param egfilmRating egfilmRating or {@code null} for none
   */
  public ContentRating setEgfilmRating(java.lang.String egfilmRating) {
    this.egfilmRating = egfilmRating;
    return this;
  }

  /**
   * Rating system in Japan - Eiga Rinri Kanri Iinkai
   * @return value or {@code null} for none
   */
  public java.lang.String getEirinRating() {
    return eirinRating;
  }

  /**
   * Rating system in Japan - Eiga Rinri Kanri Iinkai
   * @param eirinRating eirinRating or {@code null} for none
   */
  public ContentRating setEirinRating(java.lang.String eirinRating) {
    this.eirinRating = eirinRating;
    return this;
  }

  /**
   * Rating system for Malaysia - Film Censorship Board of Malaysia
   * @return value or {@code null} for none
   */
  public java.lang.String getFcbmRating() {
    return fcbmRating;
  }

  /**
   * Rating system for Malaysia - Film Censorship Board of Malaysia
   * @param fcbmRating fcbmRating or {@code null} for none
   */
  public ContentRating setFcbmRating(java.lang.String fcbmRating) {
    this.fcbmRating = fcbmRating;
    return this;
  }

  /**
   * Rating system for Hong kong - Office for Film, Newspaper and Article Administration
   * @return value or {@code null} for none
   */
  public java.lang.String getFcoRating() {
    return fcoRating;
  }

  /**
   * Rating system for Hong kong - Office for Film, Newspaper and Article Administration
   * @param fcoRating fcoRating or {@code null} for none
   */
  public ContentRating setFcoRating(java.lang.String fcoRating) {
    this.fcoRating = fcoRating;
    return this;
  }

  /**
   * Rating system in France - French Minister of Culture
   * @return value or {@code null} for none
   */
  public java.lang.String getFmocRating() {
    return fmocRating;
  }

  /**
   * Rating system in France - French Minister of Culture
   * @param fmocRating fmocRating or {@code null} for none
   */
  public ContentRating setFmocRating(java.lang.String fmocRating) {
    this.fmocRating = fmocRating;
    return this;
  }

  /**
   * Rating system for South africa - Film & Publication Board
   * @return value or {@code null} for none
   */
  public java.lang.String getFpbRating() {
    return fpbRating;
  }

  /**
   * Rating system for South africa - Film & Publication Board
   * @param fpbRating fpbRating or {@code null} for none
   */
  public ContentRating setFpbRating(java.lang.String fpbRating) {
    this.fpbRating = fpbRating;
    return this;
  }

  /**
   * Rating system in Germany - Voluntary Self Regulation of the Movie Industry
   * @return value or {@code null} for none
   */
  public java.lang.String getFskRating() {
    return fskRating;
  }

  /**
   * Rating system in Germany - Voluntary Self Regulation of the Movie Industry
   * @param fskRating fskRating or {@code null} for none
   */
  public ContentRating setFskRating(java.lang.String fskRating) {
    this.fskRating = fskRating;
    return this;
  }

  /**
   * Rating system for Greece - Greece Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getGrfilmRating() {
    return grfilmRating;
  }

  /**
   * Rating system for Greece - Greece Rating System
   * @param grfilmRating grfilmRating or {@code null} for none
   */
  public ContentRating setGrfilmRating(java.lang.String grfilmRating) {
    this.grfilmRating = grfilmRating;
    return this;
  }

  /**
   * Rating system in Spain - Instituto de Cinematografia y de las Artes Audiovisuales
   * @return value or {@code null} for none
   */
  public java.lang.String getIcaaRating() {
    return icaaRating;
  }

  /**
   * Rating system in Spain - Instituto de Cinematografia y de las Artes Audiovisuales
   * @param icaaRating icaaRating or {@code null} for none
   */
  public ContentRating setIcaaRating(java.lang.String icaaRating) {
    this.icaaRating = icaaRating;
    return this;
  }

  /**
   * Rating system in Ireland - Irish Film Classification Office
   * @return value or {@code null} for none
   */
  public java.lang.String getIfcoRating() {
    return ifcoRating;
  }

  /**
   * Rating system in Ireland - Irish Film Classification Office
   * @param ifcoRating ifcoRating or {@code null} for none
   */
  public ContentRating setIfcoRating(java.lang.String ifcoRating) {
    this.ifcoRating = ifcoRating;
    return this;
  }

  /**
   * Rating system for Israel - Israel Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getIlfilmRating() {
    return ilfilmRating;
  }

  /**
   * Rating system for Israel - Israel Rating System
   * @param ilfilmRating ilfilmRating or {@code null} for none
   */
  public ContentRating setIlfilmRating(java.lang.String ilfilmRating) {
    this.ilfilmRating = ilfilmRating;
    return this;
  }

  /**
   * Rating system for Argentina - Instituto Nacional de Cine y Artes Audiovisuales
   * @return value or {@code null} for none
   */
  public java.lang.String getIncaaRating() {
    return incaaRating;
  }

  /**
   * Rating system for Argentina - Instituto Nacional de Cine y Artes Audiovisuales
   * @param incaaRating incaaRating or {@code null} for none
   */
  public ContentRating setIncaaRating(java.lang.String incaaRating) {
    this.incaaRating = incaaRating;
    return this;
  }

  /**
   * Rating system for Kenya - Kenya Film Classification Board
   * @return value or {@code null} for none
   */
  public java.lang.String getKfcbRating() {
    return kfcbRating;
  }

  /**
   * Rating system for Kenya - Kenya Film Classification Board
   * @param kfcbRating kfcbRating or {@code null} for none
   */
  public ContentRating setKfcbRating(java.lang.String kfcbRating) {
    this.kfcbRating = kfcbRating;
    return this;
  }

  /**
   * Rating system for Netherlands - Nederlands Instituut voor de Classificatie van Audiovisuele
   * Media
   * @return value or {@code null} for none
   */
  public java.lang.String getKijkwijzerRating() {
    return kijkwijzerRating;
  }

  /**
   * Rating system for Netherlands - Nederlands Instituut voor de Classificatie van Audiovisuele
   * Media
   * @param kijkwijzerRating kijkwijzerRating or {@code null} for none
   */
  public ContentRating setKijkwijzerRating(java.lang.String kijkwijzerRating) {
    this.kijkwijzerRating = kijkwijzerRating;
    return this;
  }

  /**
   * Rating system in South Korea - Korea Media Rating Board
   * @return value or {@code null} for none
   */
  public java.lang.String getKmrbRating() {
    return kmrbRating;
  }

  /**
   * Rating system in South Korea - Korea Media Rating Board
   * @param kmrbRating kmrbRating or {@code null} for none
   */
  public ContentRating setKmrbRating(java.lang.String kmrbRating) {
    this.kmrbRating = kmrbRating;
    return this;
  }

  /**
   * Rating system for Indonesia - Lembaga Sensor Film
   * @return value or {@code null} for none
   */
  public java.lang.String getLsfRating() {
    return lsfRating;
  }

  /**
   * Rating system for Indonesia - Lembaga Sensor Film
   * @param lsfRating lsfRating or {@code null} for none
   */
  public ContentRating setLsfRating(java.lang.String lsfRating) {
    this.lsfRating = lsfRating;
    return this;
  }

  /**
   * Rating system for Malta - Film Age-Classification Board
   * @return value or {@code null} for none
   */
  public java.lang.String getMccaaRating() {
    return mccaaRating;
  }

  /**
   * Rating system for Malta - Film Age-Classification Board
   * @param mccaaRating mccaaRating or {@code null} for none
   */
  public ContentRating setMccaaRating(java.lang.String mccaaRating) {
    this.mccaaRating = mccaaRating;
    return this;
  }

  /**
   * Rating system for Denmark - The Media Council for Children and Young People
   * @return value or {@code null} for none
   */
  public java.lang.String getMccypRating() {
    return mccypRating;
  }

  /**
   * Rating system for Denmark - The Media Council for Children and Young People
   * @param mccypRating mccypRating or {@code null} for none
   */
  public ContentRating setMccypRating(java.lang.String mccypRating) {
    this.mccypRating = mccypRating;
    return this;
  }

  /**
   * Rating system for Singapore - Media Development Authority
   * @return value or {@code null} for none
   */
  public java.lang.String getMdaRating() {
    return mdaRating;
  }

  /**
   * Rating system for Singapore - Media Development Authority
   * @param mdaRating mdaRating or {@code null} for none
   */
  public ContentRating setMdaRating(java.lang.String mdaRating) {
    this.mdaRating = mdaRating;
    return this;
  }

  /**
   * Rating system for Norway - Medietilsynet
   * @return value or {@code null} for none
   */
  public java.lang.String getMedietilsynetRating() {
    return medietilsynetRating;
  }

  /**
   * Rating system for Norway - Medietilsynet
   * @param medietilsynetRating medietilsynetRating or {@code null} for none
   */
  public ContentRating setMedietilsynetRating(java.lang.String medietilsynetRating) {
    this.medietilsynetRating = medietilsynetRating;
    return this;
  }

  /**
   * Rating system for Finland - Finnish Centre for Media Education and Audiovisual Media
   * @return value or {@code null} for none
   */
  public java.lang.String getMekuRating() {
    return mekuRating;
  }

  /**
   * Rating system for Finland - Finnish Centre for Media Education and Audiovisual Media
   * @param mekuRating mekuRating or {@code null} for none
   */
  public ContentRating setMekuRating(java.lang.String mekuRating) {
    this.mekuRating = mekuRating;
    return this;
  }

  /**
   * Rating system in Italy - Ministero dei Beni e delle Attivita Culturali e del Turismo
   * @return value or {@code null} for none
   */
  public java.lang.String getMibacRating() {
    return mibacRating;
  }

  /**
   * Rating system in Italy - Ministero dei Beni e delle Attivita Culturali e del Turismo
   * @param mibacRating mibacRating or {@code null} for none
   */
  public ContentRating setMibacRating(java.lang.String mibacRating) {
    this.mibacRating = mibacRating;
    return this;
  }

  /**
   * Rating system for Colombia - MoC
   * @return value or {@code null} for none
   */
  public java.lang.String getMocRating() {
    return mocRating;
  }

  /**
   * Rating system for Colombia - MoC
   * @param mocRating mocRating or {@code null} for none
   */
  public ContentRating setMocRating(java.lang.String mocRating) {
    this.mocRating = mocRating;
    return this;
  }

  /**
   * Rating system for Taiwan - Ministry of Culture - Tawan
   * @return value or {@code null} for none
   */
  public java.lang.String getMoctwRating() {
    return moctwRating;
  }

  /**
   * Rating system for Taiwan - Ministry of Culture - Tawan
   * @param moctwRating moctwRating or {@code null} for none
   */
  public ContentRating setMoctwRating(java.lang.String moctwRating) {
    this.moctwRating = moctwRating;
    return this;
  }

  /**
   * Motion Picture Association of America rating for the content.
   * @return value or {@code null} for none
   */
  public java.lang.String getMpaaRating() {
    return mpaaRating;
  }

  /**
   * Motion Picture Association of America rating for the content.
   * @param mpaaRating mpaaRating or {@code null} for none
   */
  public ContentRating setMpaaRating(java.lang.String mpaaRating) {
    this.mpaaRating = mpaaRating;
    return this;
  }

  /**
   * Rating system for Philippines - MOVIE AND TELEVISION REVIEW AND CLASSIFICATION BOARD
   * @return value or {@code null} for none
   */
  public java.lang.String getMtrcbRating() {
    return mtrcbRating;
  }

  /**
   * Rating system for Philippines - MOVIE AND TELEVISION REVIEW AND CLASSIFICATION BOARD
   * @param mtrcbRating mtrcbRating or {@code null} for none
   */
  public ContentRating setMtrcbRating(java.lang.String mtrcbRating) {
    this.mtrcbRating = mtrcbRating;
    return this;
  }

  /**
   * Rating system for Maldives - National Bureau of Classification
   * @return value or {@code null} for none
   */
  public java.lang.String getNbcRating() {
    return nbcRating;
  }

  /**
   * Rating system for Maldives - National Bureau of Classification
   * @param nbcRating nbcRating or {@code null} for none
   */
  public ContentRating setNbcRating(java.lang.String nbcRating) {
    this.nbcRating = nbcRating;
    return this;
  }

  /**
   * Rating system for Poland - National Broadcasting Council
   * @return value or {@code null} for none
   */
  public java.lang.String getNbcplRating() {
    return nbcplRating;
  }

  /**
   * Rating system for Poland - National Broadcasting Council
   * @param nbcplRating nbcplRating or {@code null} for none
   */
  public ContentRating setNbcplRating(java.lang.String nbcplRating) {
    this.nbcplRating = nbcplRating;
    return this;
  }

  /**
   * Rating system for Bulgaria - National Film Centre
   * @return value or {@code null} for none
   */
  public java.lang.String getNfrcRating() {
    return nfrcRating;
  }

  /**
   * Rating system for Bulgaria - National Film Centre
   * @param nfrcRating nfrcRating or {@code null} for none
   */
  public ContentRating setNfrcRating(java.lang.String nfrcRating) {
    this.nfrcRating = nfrcRating;
    return this;
  }

  /**
   * Rating system for Nigeria - National Film and Video Censors Board
   * @return value or {@code null} for none
   */
  public java.lang.String getNfvcbRating() {
    return nfvcbRating;
  }

  /**
   * Rating system for Nigeria - National Film and Video Censors Board
   * @param nfvcbRating nfvcbRating or {@code null} for none
   */
  public ContentRating setNfvcbRating(java.lang.String nfvcbRating) {
    this.nfvcbRating = nfvcbRating;
    return this;
  }

  /**
   * Rating system for Latvia - National Film Center of Latvia
   * @return value or {@code null} for none
   */
  public java.lang.String getNkclvRating() {
    return nkclvRating;
  }

  /**
   * Rating system for Latvia - National Film Center of Latvia
   * @param nkclvRating nkclvRating or {@code null} for none
   */
  public ContentRating setNkclvRating(java.lang.String nkclvRating) {
    this.nkclvRating = nkclvRating;
    return this;
  }

  /**
   * Rating system in New Zealand - Office of Film and Literature Classification
   * @return value or {@code null} for none
   */
  public java.lang.String getOflcRating() {
    return oflcRating;
  }

  /**
   * Rating system in New Zealand - Office of Film and Literature Classification
   * @param oflcRating oflcRating or {@code null} for none
   */
  public ContentRating setOflcRating(java.lang.String oflcRating) {
    this.oflcRating = oflcRating;
    return this;
  }

  /**
   * Rating system for Peru - Peru Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getPefilmRating() {
    return pefilmRating;
  }

  /**
   * Rating system for Peru - Peru Rating System
   * @param pefilmRating pefilmRating or {@code null} for none
   */
  public ContentRating setPefilmRating(java.lang.String pefilmRating) {
    this.pefilmRating = pefilmRating;
    return this;
  }

  /**
   * Rating system for Hungary - Rating Committee of the National Office of Film
   * @return value or {@code null} for none
   */
  public java.lang.String getRcnofRating() {
    return rcnofRating;
  }

  /**
   * Rating system for Hungary - Rating Committee of the National Office of Film
   * @param rcnofRating rcnofRating or {@code null} for none
   */
  public ContentRating setRcnofRating(java.lang.String rcnofRating) {
    this.rcnofRating = rcnofRating;
    return this;
  }

  /**
   * Rating system for Venezuela - SiBCI
   * @return value or {@code null} for none
   */
  public java.lang.String getResorteviolenciaRating() {
    return resorteviolenciaRating;
  }

  /**
   * Rating system for Venezuela - SiBCI
   * @param resorteviolenciaRating resorteviolenciaRating or {@code null} for none
   */
  public ContentRating setResorteviolenciaRating(java.lang.String resorteviolenciaRating) {
    this.resorteviolenciaRating = resorteviolenciaRating;
    return this;
  }

  /**
   * Rating system in Mexico - General Directorate of Radio, Television and Cinematography
   * @return value or {@code null} for none
   */
  public java.lang.String getRtcRating() {
    return rtcRating;
  }

  /**
   * Rating system in Mexico - General Directorate of Radio, Television and Cinematography
   * @param rtcRating rtcRating or {@code null} for none
   */
  public ContentRating setRtcRating(java.lang.String rtcRating) {
    this.rtcRating = rtcRating;
    return this;
  }

  /**
   * Rating system for Ireland - Raidi� Teilif�s �ireann
   * @return value or {@code null} for none
   */
  public java.lang.String getRteRating() {
    return rteRating;
  }

  /**
   * Rating system for Ireland - Raidi� Teilif�s �ireann
   * @param rteRating rteRating or {@code null} for none
   */
  public ContentRating setRteRating(java.lang.String rteRating) {
    this.rteRating = rteRating;
    return this;
  }

  /**
   * Rating system in Russia
   * @return value or {@code null} for none
   */
  public java.lang.String getRussiaRating() {
    return russiaRating;
  }

  /**
   * Rating system in Russia
   * @param russiaRating russiaRating or {@code null} for none
   */
  public ContentRating setRussiaRating(java.lang.String russiaRating) {
    this.russiaRating = russiaRating;
    return this;
  }

  /**
   * Rating system for Slovakia - Slovakia Rating System
   * @return value or {@code null} for none
   */
  public java.lang.String getSkfilmRating() {
    return skfilmRating;
  }

  /**
   * Rating system for Slovakia - Slovakia Rating System
   * @param skfilmRating skfilmRating or {@code null} for none
   */
  public ContentRating setSkfilmRating(java.lang.String skfilmRating) {
    this.skfilmRating = skfilmRating;
    return this;
  }

  /**
   * Rating system for Iceland - SMAIS
   * @return value or {@code null} for none
   */
  public java.lang.String getSmaisRating() {
    return smaisRating;
  }

  /**
   * Rating system for Iceland - SMAIS
   * @param smaisRating smaisRating or {@code null} for none
   */
  public ContentRating setSmaisRating(java.lang.String smaisRating) {
    this.smaisRating = smaisRating;
    return this;
  }

  /**
   * Rating system for Sweden - Statens medier�d (National Media Council)
   * @return value or {@code null} for none
   */
  public java.lang.String getSmsaRating() {
    return smsaRating;
  }

  /**
   * Rating system for Sweden - Statens medier�d (National Media Council)
   * @param smsaRating smsaRating or {@code null} for none
   */
  public ContentRating setSmsaRating(java.lang.String smsaRating) {
    this.smsaRating = smsaRating;
    return this;
  }

  /**
   * TV Parental Guidelines rating of the content.
   * @return value or {@code null} for none
   */
  public java.lang.String getTvpgRating() {
    return tvpgRating;
  }

  /**
   * TV Parental Guidelines rating of the content.
   * @param tvpgRating tvpgRating or {@code null} for none
   */
  public ContentRating setTvpgRating(java.lang.String tvpgRating) {
    this.tvpgRating = tvpgRating;
    return this;
  }

  /**
   * Internal YouTube rating.
   * @return value or {@code null} for none
   */
  public java.lang.String getYtRating() {
    return ytRating;
  }

  /**
   * Internal YouTube rating.
   * @param ytRating ytRating or {@code null} for none
   */
  public ContentRating setYtRating(java.lang.String ytRating) {
    this.ytRating = ytRating;
    return this;
  }

  @Override
  public ContentRating set(String fieldName, Object value) {
    return (ContentRating) super.set(fieldName, value);
  }

  @Override
  public ContentRating clone() {
    return (ContentRating) super.clone();
  }

}
