source 'https://github.com/CocoaPods/Specs.git'

target 'YKMediaPlayerKit', :exclusive => true do
  pod "YKMediaPlayerKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "YKMediaPlayerKit", :path => "../"

  
end
